### ISSUE TITLE
insert copy for "Privacy Policy"-subpage

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/myne-chat-website#43]
https://docs.google.com/document/d/13ZFz9OfoNTjtXzYOcnYqq3aBNKEzVG_cLTiOrPfouTw/edit#heading=h.gjdgxs

for

https://myne-chat-website.vercel.app/privacy-policy

**Comment by CristianGomezO** [comment]
Could you give me access please?
![image](https://user-images.githubusercontent.com/41966303/151883734-51c3c383-6720-469b-a8cd-c171bf373f5b.png)

**Comment by jjperezaguinaga** [comment]
@ReinhardSchmidt have you followed-up here?

**Comment by ReinhardSchmidt** [comment]
@jjperezaguinaga @CristianGomezO granted. sorry!
