### ISSUE TITLE
Mailchimp API for the Newsletter

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/myne-chat-website#46]
For the newsletter we decided to go with mailchimp.

- Design elements should be the same like we have already: https://myne-chat-website.vercel.app
- Mailchimp API: https://mailchimp.com/developer/marketing/

For the playing with API, you can use recently created API key: `2d3e74936fd29717cd8aee4bff237d7c-us14`

**Comment by betinho89** [comment]
Do you already have a registered audience list? On mailchimp panel, because we need it, to register a new email on that audience list. If is yes, can you please provide the list ID.

**Comment by betinho89** [comment]
Also, we need the server prefix... Copy and paste the documentation:

To find the value for the server parameter used in mailchimp.setConfig, log into your Mailchimp account and look at the URL in your browser. You’ll see something like https://us19.admin.mailchimp.com/; the us19 part is the server prefix. Note that your specific value may be different.

**Comment by Jaguaras** [comment]
@betinho89 FYI we only need to collect subscribers. Then we will send out emails through the mailchimp platform, I am not sure why you need a server prefix for that.

Regarding audience list, I have a tag called: `Testing` I can see also ID: `501697`

**Comment by betinho89** [comment]
The oauth is not needed either, we already found what the value of the "server_prefix" is, and to test our code, we created a MailChimp account, and everything worked without problem, now what we need to provide us is the ID of the list of audience, we share the link, so you can get it.
https://mailchimp.com/es/help/find-audience-id/

**Comment by jjperezaguinaga** [comment]
@Jaguaras Can you follow up here? cc @ReinhardSchmidt

**Comment by Jaguaras** [comment]
Thanks @jjperezaguinaga already forwarded audience ID to @betinho89 ;)
